### ISSUE TITLE
Improving commit message titles

### ISSUE THREAD

**Issue by yin-ka** [Kgomotso196/My-Portfolio#3]
- I think you should Make use of descriptive message titles to aid understanding of the work you have done.

**Comment by kalbek** [comment]
I agree you can refer to this link for better commit message conventions.

https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/#:~:text=1%20Separate%20the%20subject%20from%20the%20body%20with,made%20and%20why%20you%20made%20them.%20More%20items

**Comment by BANCUNGUYE66** [comment]
You have done great job so far, but I think you can improve your commit message to make sense 🥇
